-- use the database
USE yvhb4mt0tabkep2l;

ALTER TABLE comment DROP FOREIGN KEY comment_ibfk_1;
ALTER TABLE comment DROP FOREIGN KEY comment_ibfk_2;

DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;

-- create the user table
CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

-- create the post table
CREATE TABLE Post (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  post_title VARCHAR(255) NOT NULL,
  post_content TEXT NOT NULL,
  post_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- create the comment table
CREATE TABLE Comment (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  comment_content TEXT NOT NULL,
  comment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE
);
